Repository SwevenSoftware/swevensoftware.github.io, pull requests merged in 2021-05, with the labels that each got.

#11 Feature/manutentore server
  _includes/prev_next.liquid
  assets/server/class_diagram.png
  assets/server/package_diagram.png
  glossario.md
  index.md
  manutentore/index.md
  manutentore/server.md
  manutentore/server/architettura.md
  manutentore/server/contribuzione.md
  manutentore/server/index.md
  manutentore/server/tecnologie.md
  manutentore/server/testing.md
  manutentore/server/utilizzo.md
  utente/server/account.md
  utente/server/prenotazioni.md
  utente/server/reports.md
  utente/server/stanze.md
  utente/server/utenti.md
Labels: documentation, enhancement

#12 added nav order in order to fix liquid file navigation
  utente/server/prenotazioni.md
  utente/server/reports.md
  utente/server/stanze.md
  utente/server/utenti.md
Labels: documentation

#19 Android maintainer manual
  index.md
  manutentore/android.md
  manutentore/android/architettura.md
  manutentore/android/contribuzione.md
  manutentore/android/index.md
  manutentore/android/installazione.md
  manutentore/android/tecnologie.md
  manutentore/android/testing.md
  manutentore/index.md
Labels: documentation, enhancement

#18 Android user manual
  assets/android/app_screenshots/cleaner_account.png
  assets/android/app_screenshots/cleaner_rooms.png
  assets/android/app_screenshots/desk_unavailable.png
  assets/android/app_screenshots/edit_reservation.png
  assets/android/app_screenshots/empty_home.png
  assets/android/app_screenshots/login.png
  assets/android/app_screenshots/notification.png
  assets/android/app_screenshots/password.png
  assets/android/app_screenshots/reservation.png
  assets/android/app_screenshots/reservation_end.png
  assets/android/app_screenshots/reservation_start.png
  assets/android/app_screenshots/reservations_list.png
  assets/android/app_screenshots/rfid_reservation.png
  assets/android/app_screenshots/rfid_scan.png
  assets/android/app_screenshots/room_view.png
  assets/android/app_screenshots/settings.png
  assets/android/app_screenshots/user_account.png
  assets/android/app_screenshots/user_rooms.png
  utente/android.md
  utente/android/cleaner.md
  utente/android/index.md
  utente/android/user.md
  utente/index.md
  utente/server/index.md
Labels: documentation, enhancement

#21 Uniform indexes
  manutentore/android/architettura.md
  manutentore/android/contribuzione.md
  manutentore/android/index.md
  manutentore/android/installazione.md
  manutentore/android/tecnologie.md
  manutentore/android/testing.md
  manutentore/server/architettura.md
  manutentore/server/contribuzione.md
  manutentore/server/index.md
  manutentore/server/tecnologie.md
  manutentore/server/testing.md
  manutentore/server/utilizzo.md
  manutentore/web/architettura.md
  manutentore/web/contribuzione.md
  manutentore/web/index.md
  manutentore/web/tecnologie.md
  manutentore/web/testing.md
  manutentore/web/utilizzo.md
  utente/android/cleaner.md
  utente/android/index.md
  utente/android/user.md
  utente/server/account.md
  utente/server/index.md
  utente/server/prenotazioni.md
  utente/server/reports.md
  utente/server/stanze.md
  utente/server/utenti.md
Labels: enhancement

#20 Corrected web maintainer manual section
  manutentore/web/architettura.md
  manutentore/web/contribuzione.md
  manutentore/web/index.md
  manutentore/web/tecnologie.md
  manutentore/web/testing.md
  manutentore/web/utilizzo.md
Labels: bug, documentation

#16 Created web user manual and added chapters and images
  assets/web/createRoom.gif
  assets/web/deleteRoom.gif
  assets/web/deleteUser.gif
  assets/web/hamburger.gif
  assets/web/login.gif
  assets/web/makeGif.sh
  assets/web/modifyRoom.gif
  assets/web/modifyUser.gif
  assets/web/newUser.gif
  assets/web/web_scheme.png
  utente/android/cleaner.md
  utente/android/user.md
  utente/server/index.md
  utente/web.md
  utente/web/Login.md
  utente/web/Navigazione.md
  utente/web/PaginaStanze.md
  utente/web/PaginaUtenti.md
  utente/web/index.md
Labels: documentation, enhancement

#24 added android and web badges in the front page
  index.md
Labels: documentation, enhancement

#23 aggiunta chiamata API per il reportimento di report gia creati
  utente/server/reports.md
Labels: documentation

#25 Aggiunte strategie di deploy tramite il bundling dell'app
  manutentore/android/installazione.md
Labels: documentation, enhancement
